#!/bin/sh



check_python3() {
  python3 -m py_compile "$1"
  return $?
}

check_shell() {
  sh -n "$1"
  return $?
}
check_bash() {
  bash -n "$1"
}
check_dash() {
  dash -n "$1"
}



check_file() {
  [ -d "$1" ] && return 0
  case "$1" in
  *.py)
    echo "python3"
    return 0
    ;;
  esac
  if [ -x "$1" ] ; then
    local hashbang=$(head -1 "$1")
    case "$hashbang" in
      \#!/bin/sh*)
        echo "shell"
        return 0
        ;;
      \#!/bin/bash*)
        echo "bash"
        return 0
        ;;
      \#!/bin/dash*)
        echo "dash"
        return 0
        ;;
    esac
  fi
  echo ""
  return 0
}

find . -path ./.git -prune -o -type f  | (
  return=0
  while read script
  do
    op=$(check_file "$script")
    [ -z "$op" ] && continue
    echo -n "$script: "
    if check_"$op" "$script" ; then
      echo "OK"
    else
      return=1
    fi
  done
)
