#!/bin/sh
#
# tags:iptables
# target::/usr/local/bin/
# mode:755
#

set -euf -o pipefail
usage() {
  cat <<-EOF
	Usage: $0 [options]

	- -4 file : IPv4 rule file
	- -6 file : IPv6 rule file
	- -v : verbose
	- -q : quiet
	EOF
  exit
}
die() {
  local rc="$1" ; shift
  echo "$@" 1>&2
  exit $rc
}
(( type iptables-save && type iptables-restore )>/dev/null 2>&1 || ( type ip6tables-save && type ip6tables-restore )>/dev/null 2>&1 ) || die 7 "Missing iptables support"

ip4rules=""
ip6rules=""
verbose="echo"

[ $# -eq 0 ] && usage
while [ $# -gt 0 ]
do
  case "$1" in
  -4)
    [ $# -eq 1 ] && die 26 "No file specified for option $1"
    ip4rules="$2" ; shift
    ;;
  -6)
    [ $# -eq 1 ] && die 26 "No file specified for option $1"
    ip6rules="$2" ; shift
    ;;
  -v)
    verbose=echo
    ;;
  -q)
    verbose=:
    ;;
  *)
    usage
    ;;
  esac
  shift
done

if [ -z "$ip4rules" ] && [ -z "$ip6rules" ] ; then
  die 52 "No rules file specified, use -4 or -6 options"
fi

check_file() {
  local proto="$1" file="$2"
  [ -z "$file" ] && return 0
  [ ! -r "$file" ] && die 57 "$file: not readable"
  # Check syntax...
  ip${proto}tables-restore --test "$file" || die 60 "File format error"
}

check_file "" "$ip4rules"
check_file 6 "$ip6rules"

$verbose Applying configuration...

ip4save="$(iptables-save -c)"
ip6save="$(ip6tables-save -c)"

rollback() {
  $verbose ''
  $verbose 'Rolling back changes...'
  ($verbose 'IPv4 tables' ; echo "$ip4save" | iptables-restore -c) || :
  ($verbose 'IPv6 tables' ; echo "$ip6save" | ip6tables-restore -c) || :
}

trap 'rollback' EXIT
for i in INT HUP
do
  trap 'rollback;exit' SIG$i
done

[ -n "$ip4rules" ] && iptables-restore "$ip4rules"
[ -n "$ip6rules" ] && ip6tables-restore "$ip6rules"

sleep 3 # Give it some time to mess-up...

while true
do
  echo -n "Enter \"ok\" to commit (Ctrl+C) to revert: "
  if read -t 30 input ; then
    if [ x"$input" = x"ok" ] ; then
      # OK, commiting changes...
      trap "" EXIT
      exit 0
    fi
  else
    $verbose timed-out
    exit # This will roll back
  fi
done


